-- Create Snowpipe to automatically ingest data from S3 into staging table
CREATE OR REPLACE PIPE FORMULAONE_STAGING.PROCESSENGINE.RACEDETAILS_SNOWPIPE
  AUTO_INGEST = TRUE
  AS
 COPY INTO FORMULAONE_STAGING.PROCESSENGINE.RACEDETAILS
FROM @FORMULAONE_STAGING.PROCESSENGINE.RACEDETAILS_S3_STAGE
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE);

-- Describe the pipe to ensure it was created correctly
DESC PIPE FORMULAONE_STAGING.PROCESSENGINE.RACEDETAILS_SNOWPIPE;
